Repository wecode-bootcamp-korea/15-1st-Youngchapedia-backend, pull requests merged in 2020-12, with the labels that each got.

#1 `youngchapedia/settings.py` middleware 오류 수정
  youngchapedia/settings.py
Labels: Status: 리뷰 요청

#3 Add: App 및 models.py 생성
  archive/__init__.py
  archive/admin.py
  archive/apps.py
  archive/migrations/0001_initial.py
  archive/migrations/__init__.py
  archive/models.py
  archive/tests.py
  archive/views.py
  collection/__init__.py
  collection/admin.py
  collection/apps.py
  collection/migrations/0001_initial.py
  collection/migrations/__init__.py
  collection/models.py
  collection/tests.py
  collection/views.py
  content/__init__.py
  content/admin.py
  content/apps.py
  content/migrations/0001_initial.py
  content/migrations/0002_auto_20201216_1744.py
  content/migrations/0003_auto_20201216_1815.py
  content/migrations/__init__.py
  content/models.py
  content/tests.py
  content/views.py
  review/__init__.py
  review/admin.py
  review/apps.py
  review/migrations/0001_initial.py
  review/migrations/__init__.py
  review/models.py
  review/tests.py
  review/views.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/views.py
  youngchapedia/settings.py
Labels: Status: 수정 요청

#4 signup/signin 기능 추가
  review/urls.py
  user/migrations/0002_auto_20201217_0116.py
  user/models.py
  user/urls.py
  user/utils.py
  user/views.py
  youngchapedia/urls.py
Labels: Status: 리뷰 요청

#8 [이재혁] Add: 영화 별점 기능(Rating)
  archive/.views.py.swp
  archive/models.py
  archive/urls.py
  archive/views.py
  user/utils.py
  youngchapedia/urls.py
Labels: Status: 리뷰 요청

#5 [15기 김순태] Modified: api 수정사항 반영
  .gitignore
  archive/migrations/0002_auto_20201220_1806.py
  content/urls.py
  content/views.py
  pull_request_template.md
  requirements.txt
  user/migrations/0003_auto_20201220_1806.py
  user/utils.py
  user/views.py
  youngchapedia/settings.py
  youngchapedia/urls.py
Labels: Status: 수정 요청

#13 [15기 이재혁] Fix: youngchapedia.urls.py 오류 수정
  review/urls.py
  youngchapedia/urls.py
Labels: Status: 리뷰 요청

#14 [15기 이재혁] Modify: 영화별 평균 rating 연산 기능 함수화
  archive/.models.py.swp
  archive/.urls.py.swp
  archive/urls.py
  archive/utils.py
  archive/views.py
  user/utils.py
Labels: Status: 리뷰 요청

#11 [15기 김순태] Add: 검색 API 구현 (title_korean / people_name) 검색
  .DS_Store
  .gitignore
  content/.DS_Store
  content/urls.py
  content/views.py
Labels: Status: 리뷰 요청

#15 [15기 이재혁] Fix: User별 Archive 조회 기능 요청 방식 변경
  archive/views.py
Labels: Status: Accepted

#10 [15기 김순태] Add: 추가 API 구현 (서비스, 상세페이지)
  .DS_Store
  archive/views.py
  content/.DS_Store
  content/urls.py
  content/views.py
Labels: Status: Accepted

#12 [15기 이재혁] Add: review CRUD 기능
  content/urls.py
  review/.urls.py.swp
  review/migrations/0002_auto_20201218_1849.py
  review/models.py
  review/urls.py
  review/views.py
  user/utils.py
  youngchapedia/settings.py
  youngchapedia/urls.py
Labels: Status: 리뷰 요청
